version: '{build}'

os: Visual Studio 2015

build_script:
- CALL dotnet restore
- CALL dotnet publish --configuration Release --output "%APPVEYOR_BUILD_FOLDER%\artifacts\publish"
- CALL .\publish_to_nuget.cmd

artifacts:
- path: artifacts/publish
  name: Web application

environment:
  deploy_server:
    secure: 7f9bcFkXgx37td51cnPI9A==
  deploy_username:
    secure: +4+0JDINyo6SMCl7QDFxjA==
  deploy_password:
    secure: RHmwJ0TuDaknqQdBiIUtYiO6NSmxqEbXDACMtJG16W4=
  nuget_key:
    secure: 7STw7NoWh/5V4LBPzBeXtikLJgAsL+ZikyOKSJqiksM9ZcilhaSFGFawGEeml3WT

deploy_script:
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:recycleApp -dest:recycleApp=Haufwerk,recycleMode=StopAppPool,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath=%APPVEYOR_BUILD_FOLDER%\artifacts\publish -dest:contentPath=Haufwerk,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:recycleApp -dest:recycleApp=Haufwerk,recycleMode=StartAppPool,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%