version: '{build}'

os: Visual Studio 2015

install:
- dnvm install -arch x64 1.0.0-rc1-update1
- dnu restore --quiet ".\src\Haufwerk.Client"
- dnu restore --quiet ".\src\Haufwerk"

build_script:
- SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- CALL dnu publish ".\src\Haufwerk" --out "%APPVEYOR_BUILD_FOLDER%\artifacts\publish" --configuration Release --no-source --runtime dnx-clr-win-x64.1.0.0-rc1-update1 --wwwroot-out "wwwroot" --quiet
- CALL dnu pack ".\src\Haufwerk.Client" --configuration Release > nul

artifacts:
- path: artifacts/publish
  name: Web application

environment:
  deploy_server:
    secure: 7f9bcFkXgx37td51cnPI9A==
  deploy_username:
    secure: +4+0JDINyo6SMCl7QDFxjA==
  deploy_password:
    secure: RHmwJ0TuDaknqQdBiIUtYiO6NSmxqEbXDACMtJG16W4=
  nuget_key:
    secure: 7STw7NoWh/5V4LBPzBeXtikLJgAsL+ZikyOKSJqiksM9ZcilhaSFGFawGEeml3WT

deploy_script:
- CALL nuget push ".\src\Haufwerk.Client\bin\Release\*.nupkg" %nuget_key%
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:recycleApp -dest:recycleApp=Haufwerk,recycleMode=StopAppPool,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath=%APPVEYOR_BUILD_FOLDER%\artifacts\publish\wwwroot -dest:contentPath=Haufwerk,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPathLib=%APPVEYOR_BUILD_FOLDER%\artifacts\publish\approot -dest:contentPathLib=Haufwerk,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:recycleApp -dest:recycleApp=Haufwerk,recycleMode=StartAppPool,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%